### ISSUE TITLE
Show と入力すると これまで自分が作成した guest item が5件表示され修正できる

### ISSUE THREAD

**Issue by mkeeda** [colorfultalk/ct_prototype#21]
guestが登録したitemを編集するためには，guestのitemが一覧できる必要がある．
APIサーバ側には `api/guest-items/`があって，ここにGETすればguestのitemが取得できる．
しかし，client.pyにはこのAPIにGETアクセスするメソッドがない．

**Comment by Yoshiharu-Ikutani** [comment]
/api/guest-myitems として実装します．
